import type { Announcement, Product, StoreShape, Worker } from "./types";

const createdAt = "2026-05-02T00:00:00.000Z";
const serviceDescription =
  "当前为测试版商品页面，详细服务说明后续补充。下单前请确认需求并保持页面可联系。平台禁止外挂、脚本、BUG、盗号等违规行为。";
const defaultProductImage = "/images/products/default-product.jpg";

const product = (
  id: string,
  name: string,
  category: Product["category"],
  price: 1 | 0.5,
  sales: number,
  description: string,
  tags: string[],
): Product => ({
  id,
  name,
  category,
  priceRmb: price,
  priceLockeCoin: price,
  sales,
  imageUrl: defaultProductImage,
  tags,
  description,
  serviceDescription,
  status: "on",
  createdAt,
});

export const initialProducts: Product[] = [
  product("product-shiny-service", "指定异色", "异色专区", 1, 188, "适合有指定异色需求的用户，当前为测试版商品。", ["异色", "指定"]),
  product("shiny-random", "随机异色", "异色专区", 0.5, 126, "适合随机异色协助需求，具体范围后续补充。", ["异色", "随机"]),
  product("shiny-all", "全部异色", "异色专区", 1, 98, "适合更完整的异色目标协助需求，当前为测试商品。", ["异色", "全部"]),

  product("pvp-trainee-basic", "见习-初级", "PVP专区", 0.5, 86, "适合 PVP 段位提升需求的玩家。", ["PVP", "段位"]),
  product("pvp-basic-mid", "初级-中级", "PVP专区", 0.5, 92, "支持不同阶段的对战协助与上分服务。", ["PVP", "上分"]),
  product("pvp-mid-high", "中级-高级", "PVP专区", 1, 108, "当前为测试商品，详细说明后续补充。", ["PVP", "进阶"]),
  product("pvp-high-special", "高级-特级", "PVP专区", 1, 76, "适合希望继续提升段位表现的玩家。", ["PVP", "协助"]),
  product("pvp-special-chief", "特级-首席", "PVP专区", 1, 66, "面向高阶段 PVP 目标的人工协助服务。", ["PVP", "高阶"]),
  product("pvp-chief-master", "首席-大师", "PVP专区", 1, 54, "适合首席到大师阶段的测试服务商品。", ["PVP", "大师"]),
  product("pvp-zero-chief", "0-首席", "PVP专区", 1, 88, "适合从基础阶段开始规划 PVP 目标的用户。", ["PVP", "整段"]),
  product("pvp-zero-master", "0-大师", "PVP专区", 1, 72, "适合完整阶段 PVP 协助需求的测试商品。", ["PVP", "热门"]),
  product("pvp-hot-team", "热门队伍", "PVP专区", 0.5, 118, "热门队伍搭配与对战思路协助，当前为测试商品。", ["队伍", "热门"]),

  product("play-fun", "娱乐陪", "陪玩专区", 0.5, 135, "提供轻松陪伴、聊天、任务、娱乐游玩体验。", ["陪玩", "轻松"]),
  product("play-skill", "技术陪", "陪玩专区", 1, 112, "提供更高执行度和更强配合度的陪玩服务。", ["陪玩", "技术"]),

  product("resource-anchor", "锚点解锁", "资源专区", 0.5, 98, "适合地图与功能解锁需求。", ["地图", "解锁"]),
  product("resource-level", "等级提升", "资源专区", 0.5, 156, "适合角色成长阶段的基础提升。", ["成长", "等级"]),
  product("resource-star", "眠枭之星", "资源专区", 1, 95, "适合眠枭之星相关材料收集与进度整理需求。", ["收集", "活动"]),
  product("resource-dungeon", "副本托管", "资源专区", 1, 143, "适合日常副本与指定副本基础协助。", ["副本", "托管"]),
  product("resource-daily", "日常接管", "资源专区", 1, 168, "适合日常任务、清体力和基础托管需求。", ["日常", "托管"]),
  product("resource-full", "全力接管", "资源专区", 1, 128, "适合需要更完整托管协助的用户。", ["托管", "完整"]),
  product("resource-flower", "跑花服务", "资源专区", 0.5, 86, "适合跑花相关基础协助需求，当前为测试商品。", ["跑图", "跑花"]),
  product("resource-mine", "跑矿服务", "资源专区", 0.5, 82, "适合跑矿相关基础协助需求，当前为测试商品。", ["跑图", "跑矿"]),
  product("resource-locke-coin", "洛克贝服务", "资源专区", 1, 118, "适合洛克贝相关服务记录测试，正式规则后续补充。", ["洛克贝", "资源"]),
];

export const initialWorkers: Worker[] = [
  {
    id: "worker-silver-fish",
    name: "双灯鱼",
    avatarUrl: "",
    gender: "unknown",
    level: "金牌",
    onlineStatus: "online",
    intro: "沟通耐心，擅长异色、资源和日常协助，反馈节奏稳定。",
    completedOrderCount: 328,
    rating: 99,
    dynamicText: "在线接单中，欢迎备注清楚需求。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-futu",
    name: "浮屠",
    avatarUrl: "",
    gender: "male",
    level: "银牌",
    onlineStatus: "online",
    intro: "擅长 PVP 与资源类协助，适合目标明确的订单。",
    completedOrderCount: 246,
    rating: 97,
    dynamicText: "今日可接 PVP 与资源专区订单。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-shenyin",
    name: "神隐",
    avatarUrl: "",
    gender: "unknown",
    level: "明星",
    onlineStatus: "offline",
    intro: "明星接单员，擅长高要求托管与复杂目标拆解。",
    completedOrderCount: 512,
    rating: 99,
    dynamicText: "暂时离线，开放后会优先处理预约需求。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-lishang",
    name: "离殇",
    avatarUrl: "",
    gender: "female",
    level: "铜牌",
    onlineStatus: "online",
    intro: "适合日常任务、陪玩和基础资源协助，服务节奏轻松。",
    completedOrderCount: 146,
    rating: 95,
    dynamicText: "在线中，适合轻量订单。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-storm",
    name: "风暴",
    avatarUrl: "",
    gender: "male",
    level: "见习",
    onlineStatus: "online",
    intro: "见习接单员，适合简单陪玩、日常和基础资源需求。",
    completedOrderCount: 58,
    rating: 93,
    dynamicText: "在线练习接单中，会认真确认需求。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: "announcement-welcome",
    title: "测试版公告",
    content: "欢迎来到小洛克电竞，当前为测试版本，部分功能与内容正在逐步完善中。",
    status: "published",
    createdAt,
  },
];

export const initialStore: StoreShape = {
  users: [],
  products: initialProducts,
  workers: initialWorkers,
  announcements: initialAnnouncements,
  orders: [],
  wallet_accounts: [],
  wallet_ledger: [],
  recharge_orders: [],
  chat_sessions: [],
  chat_messages: [],
};
