import type { AdminMenu, AdminRole, AdminUser, Announcement, Product, ProductCategoryRecord, RechargePackage, StoreShape, Worker } from "./types";

const createdAt = "2026-05-02T00:00:00.000Z";
const serviceDescription =
  "当前为测试版商品页面，详细服务说明后续补充。下单前请确认需求并保持页面可联系。平台禁止外挂、脚本、BUG、盗号等违规行为。";
const defaultProductImage = "/images/products/default-product.jpg";

const product = (
  id: string,
  name: string,
  category: Product["category"],
  price: 1 | 0.5,
  sales: number,
  description: string,
  tags: string[],
): Product => ({
  id,
  name,
  shortDescription: description,
  category,
  categoryId: category,
  priceRmb: price,
  priceLockeCoin: price,
  costPrice: 0,
  sales,
  virtualSales: 0,
  realSales: sales,
  imageUrl: defaultProductImage,
  detailImages: [],
  tags,
  description,
  serviceDescription,
  servicePort: "mobile",
  sortOrder: sales,
  isRecommended: sales >= 120,
  purchaseLimitEnabled: false,
  purchaseLimitPerUser: 1,
  deleted: false,
  workerIncomeType: "fixed",
  workerIncomeAmount: price,
  estimatedDuration: "预计 24 小时内完成",
  requireGameId: true,
  requireGameNickname: true,
  requireRemark: false,
  allowAssignedWorker: true,
  status: "on",
  createdAt,
  updatedAt: createdAt,
});

export const initialProducts: Product[] = [
  product("product-shiny-service", "指定异色", "异色专区", 1, 188, "适合有指定异色需求的用户，当前为测试版商品。", ["异色", "指定"]),
  product("shiny-random", "随机异色", "异色专区", 0.5, 126, "适合随机异色协助需求，具体范围后续补充。", ["异色", "随机"]),
  product("shiny-all", "全部异色", "异色专区", 1, 98, "适合更完整的异色目标协助需求，当前为测试商品。", ["异色", "全部"]),

  product("pvp-trainee-basic", "见习-初级", "PVP专区", 0.5, 86, "适合 PVP 段位提升需求的玩家。", ["PVP", "段位"]),
  product("pvp-basic-mid", "初级-中级", "PVP专区", 0.5, 92, "支持不同阶段的对战协助与上分服务。", ["PVP", "上分"]),
  product("pvp-mid-high", "中级-高级", "PVP专区", 1, 108, "当前为测试商品，详细说明后续补充。", ["PVP", "进阶"]),
  product("pvp-high-special", "高级-特级", "PVP专区", 1, 76, "适合希望继续提升段位表现的玩家。", ["PVP", "协助"]),
  product("pvp-special-chief", "特级-首席", "PVP专区", 1, 66, "面向高阶段 PVP 目标的人工协助服务。", ["PVP", "高阶"]),
  product("pvp-chief-master", "首席-大师", "PVP专区", 1, 54, "适合首席到大师阶段的测试服务商品。", ["PVP", "大师"]),
  product("pvp-zero-chief", "0-首席", "PVP专区", 1, 88, "适合从基础阶段开始规划 PVP 目标的用户。", ["PVP", "整段"]),
  product("pvp-zero-master", "0-大师", "PVP专区", 1, 72, "适合完整阶段 PVP 协助需求的测试商品。", ["PVP", "热门"]),
  product("pvp-hot-team", "热门队伍", "PVP专区", 0.5, 118, "热门队伍搭配与对战思路协助，当前为测试商品。", ["队伍", "热门"]),

  product("play-fun", "娱乐陪", "陪玩专区", 0.5, 135, "提供轻松陪伴、聊天、任务、娱乐游玩体验。", ["陪玩", "轻松"]),
  product("play-skill", "技术陪", "陪玩专区", 1, 112, "提供更高执行度和更强配合度的陪玩服务。", ["陪玩", "技术"]),

  product("resource-anchor", "锚点解锁", "资源专区", 0.5, 98, "适合地图与功能解锁需求。", ["地图", "解锁"]),
  product("resource-level", "等级提升", "资源专区", 0.5, 156, "适合角色成长阶段的基础提升。", ["成长", "等级"]),
  product("resource-star", "眠枭之星", "资源专区", 1, 95, "适合眠枭之星相关材料收集与进度整理需求。", ["收集", "活动"]),
  product("resource-dungeon", "副本托管", "资源专区", 1, 143, "适合日常副本与指定副本基础协助。", ["副本", "托管"]),
  product("resource-daily", "日常接管", "资源专区", 1, 168, "适合日常任务、清体力和基础托管需求。", ["日常", "托管"]),
  product("resource-full", "全力接管", "资源专区", 1, 128, "适合需要更完整托管协助的用户。", ["托管", "完整"]),
  product("resource-flower", "跑花服务", "资源专区", 0.5, 86, "适合跑花相关基础协助需求，当前为测试商品。", ["跑图", "跑花"]),
  product("resource-mine", "跑矿服务", "资源专区", 0.5, 82, "适合跑矿相关基础协助需求，当前为测试商品。", ["跑图", "跑矿"]),
  product("resource-locke-coin", "洛克贝服务", "资源专区", 1, 118, "适合洛克贝相关服务记录测试，正式规则后续补充。", ["洛克贝", "资源"]),
];

export const initialWorkers: Worker[] = [
  {
    id: "worker-silver-fish",
    name: "双灯鱼",
    avatarUrl: "",
    gender: "unknown",
    level: "金牌",
    onlineStatus: "online",
    status: "normal",
    depositStatus: "paid",
    servicePort: "both",
    depositAmount: 100,
    platformCommissionRate: 20,
    createdAt,
    updatedAt: createdAt,
    intro: "沟通耐心，擅长异色、资源和日常协助，反馈节奏稳定。",
    completedOrderCount: 328,
    rating: 99,
    dynamicText: "在线接单中，欢迎备注清楚需求。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-futu",
    name: "星火",
    avatarUrl: "",
    gender: "male",
    level: "银牌",
    onlineStatus: "online",
    status: "normal",
    depositStatus: "paid",
    servicePort: "mobile",
    depositAmount: 100,
    platformCommissionRate: 20,
    createdAt,
    updatedAt: createdAt,
    intro: "擅长 PVP 与资源类协助，适合目标明确的订单。",
    completedOrderCount: 246,
    rating: 97,
    dynamicText: "今日可接 PVP 与资源专区订单。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-shenyin",
    name: "妮蔻",
    avatarUrl: "",
    gender: "unknown",
    level: "明星",
    onlineStatus: "offline",
    status: "normal",
    depositStatus: "paid",
    servicePort: "both",
    depositAmount: 100,
    platformCommissionRate: 20,
    createdAt,
    updatedAt: createdAt,
    intro: "明星接单员，擅长高要求托管与复杂目标拆解。",
    completedOrderCount: 512,
    rating: 99,
    dynamicText: "暂时离线，开放后会优先处理预约需求。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-lishang",
    name: "清禾",
    avatarUrl: "",
    gender: "female",
    level: "铜牌",
    onlineStatus: "online",
    status: "normal",
    depositStatus: "paid",
    servicePort: "mobile",
    depositAmount: 100,
    platformCommissionRate: 20,
    createdAt,
    updatedAt: createdAt,
    intro: "适合日常任务、陪玩和基础资源协助，服务节奏轻松。",
    completedOrderCount: 146,
    rating: 95,
    dynamicText: "在线中，适合轻量订单。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
  {
    id: "worker-storm",
    name: "橙子",
    avatarUrl: "",
    gender: "male",
    level: "见习",
    onlineStatus: "online",
    status: "normal",
    depositStatus: "unpaid",
    servicePort: "pc",
    depositAmount: 0,
    platformCommissionRate: 20,
    createdAt,
    updatedAt: createdAt,
    intro: "见习接单员，适合简单陪玩、日常和基础资源需求。",
    completedOrderCount: 58,
    rating: 93,
    dynamicText: "在线练习接单中，会认真确认需求。",
    availableBalance: 0,
    totalEarned: 0,
    serviceIncome: 0,
    tipIncome: 0,
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: "announcement-welcome",
    title: "测试版公告",
    type: "notice",
    visibleTo: "all",
    coverImage: "",
    content: "欢迎来到小洛克电竞，当前为测试版本，部分功能与内容正在逐步完善中。",
    isPinned: true,
    sortOrder: 10,
    status: "published",
    viewCount: 0,
    publishAt: createdAt,
    expireAt: "",
    deleted: false,
    createdAt,
    updatedAt: createdAt,
  },
];

export const initialProductCategories: ProductCategoryRecord[] = [
  { id: "cat-shiny", parentId: null, name: "异色专区", iconUrl: "", sortOrder: 10, status: "on", createdAt, updatedAt: createdAt },
  { id: "cat-pvp", parentId: null, name: "PVP专区", iconUrl: "", sortOrder: 20, status: "on", createdAt, updatedAt: createdAt },
  { id: "cat-play", parentId: null, name: "陪玩专区", iconUrl: "", sortOrder: 30, status: "on", createdAt, updatedAt: createdAt },
  { id: "cat-resource", parentId: null, name: "资源专区", iconUrl: "", sortOrder: 40, status: "on", createdAt, updatedAt: createdAt },
];

export const initialRechargePackages: RechargePackage[] = [
  { id: "recharge-package-50", sortOrder: 10, amountRmb: 50, bonusLockeCoin: 0, amountLockeCoin: 50, status: "active", deleted: false, createdAt, updatedAt: createdAt },
  { id: "recharge-package-100", sortOrder: 20, amountRmb: 100, bonusLockeCoin: 5, amountLockeCoin: 105, status: "active", deleted: false, createdAt, updatedAt: createdAt },
  { id: "recharge-package-300", sortOrder: 30, amountRmb: 300, bonusLockeCoin: 30, amountLockeCoin: 330, status: "active", deleted: false, createdAt, updatedAt: createdAt },
  { id: "recharge-package-500", sortOrder: 40, amountRmb: 500, bonusLockeCoin: 60, amountLockeCoin: 560, status: "active", deleted: false, createdAt, updatedAt: createdAt },
];

const adminMenu = (
  id: string,
  parentId: string | null,
  type: AdminMenu["type"],
  name: string,
  path: string,
  permissionKey: string,
  sortOrder: number,
  hidden = false,
): AdminMenu => ({
  id,
  parentId,
  type,
  name,
  routeName: id.replace(/-/g, "_"),
  path,
  componentPath: "",
  icon: "",
  externalUrl: "",
  activePath: "",
  sortOrder,
  visible: !hidden,
  cache: false,
  hidden,
  embedded: false,
  hiddenTag: false,
  permissionKey,
  status: hidden ? "hidden" : "visible",
  createdAt,
  updatedAt: createdAt,
  builtIn: true,
});

export const initialAdminMenus: AdminMenu[] = [
  adminMenu("menu-dashboard", null, "directory", "统计", "/admin/dashboard", "dashboard.view", 1000),
  adminMenu("menu-dashboard-main", "menu-dashboard", "menu", "综合面板", "/admin/dashboard", "dashboard.view", 990),
  adminMenu("menu-order-statistics", "menu-dashboard", "menu", "订单统计", "/admin/order-statistics", "statistics.view", 980),
  adminMenu("btn-statistics-export", "menu-order-statistics", "button", "导出", "", "statistics.export", 970, true),

  adminMenu("menu-users", null, "directory", "用户", "/admin/users", "users.view", 900),
  adminMenu("menu-users-list", "menu-users", "menu", "用户列表", "/admin/users", "users.view", 890),
  adminMenu("menu-member-levels", "menu-users", "menu", "会员等级", "/admin/users/member-levels", "users.member_levels.manage", 880),
  adminMenu("btn-users-edit", "menu-users-list", "button", "编辑用户", "", "users.edit", 879, true),
  adminMenu("btn-users-freeze", "menu-users-list", "button", "封禁", "", "users.freeze", 878, true),
  adminMenu("btn-users-unfreeze", "menu-users-list", "button", "解封", "", "users.unfreeze", 877, true),
  adminMenu("btn-users-adjust", "menu-users-list", "button", "调账", "", "users.adjust_balance", 876, true),

  adminMenu("menu-orders", null, "directory", "订单", "/admin/orders", "orders.view", 800),
  adminMenu("menu-orders-list", "menu-orders", "menu", "订单列表", "/admin/orders", "orders.view", 790),
  adminMenu("menu-orders-create", "menu-orders", "menu", "后台派单", "/admin/orders/create", "orders.create", 780),
  adminMenu("menu-order-detail", "menu-orders", "menu", "订单详情", "/admin/order", "orders.view", 770, true),
  adminMenu("btn-orders-assign", "menu-orders-list", "button", "派单", "", "orders.assign", 769, true),
  adminMenu("btn-orders-settle", "menu-orders-list", "button", "管理员结单", "", "orders.settle", 768, true),
  adminMenu("btn-orders-refund", "menu-orders-list", "button", "退款给顾客", "", "orders.refund", 767, true),
  adminMenu("btn-orders-close", "menu-orders-list", "button", "关闭订单", "", "orders.close", 766, true),
  adminMenu("btn-orders-export", "menu-orders-list", "button", "导出订单", "", "orders.export", 765, true),

  adminMenu("menu-products", null, "directory", "商品", "/admin/products", "products.view", 700),
  adminMenu("menu-products-list", "menu-products", "menu", "商品列表", "/admin/products", "products.view", 690),
  adminMenu("menu-products-create", "menu-products", "menu", "新增商品", "/admin/product/create", "products.create", 680, true),
  adminMenu("menu-products-category", "menu-products", "menu", "商品分类", "/admin/product-categories", "products.category_manage", 670),
  adminMenu("menu-product-detail", "menu-products", "menu", "商品详情", "/admin/product", "products.view", 660, true),
  adminMenu("btn-products-edit", "menu-products-list", "button", "编辑商品", "", "products.edit", 659, true),
  adminMenu("btn-products-delete", "menu-products-list", "button", "删除商品", "", "products.delete", 658, true),
  adminMenu("btn-products-publish", "menu-products-list", "button", "上架商品", "", "products.publish", 657, true),
  adminMenu("btn-products-unpublish", "menu-products-list", "button", "下架商品", "", "products.unpublish", 656, true),

  adminMenu("menu-workers", null, "directory", "接单员", "/admin/workers", "workers.view", 600),
  adminMenu("menu-workers-list", "menu-workers", "menu", "接单员列表", "/admin/workers", "workers.view", 590),
  adminMenu("menu-worker-detail", "menu-workers", "menu", "接单员详情", "/admin/worker", "workers.view", 580, true),
  adminMenu("btn-workers-edit", "menu-workers-list", "button", "编辑接单员", "", "workers.edit", 579, true),
  adminMenu("btn-workers-freeze", "menu-workers-list", "button", "冻结接单员", "", "workers.freeze", 578, true),
  adminMenu("btn-workers-unfreeze", "menu-workers-list", "button", "解冻接单员", "", "workers.unfreeze", 577, true),
  adminMenu("btn-workers-deposit", "menu-workers-list", "button", "保证金调整", "", "workers.deposit_adjust", 576, true),
  adminMenu("btn-workers-balance", "menu-workers-list", "button", "余额调整", "", "workers.balance_adjust", 575, true),
  adminMenu("btn-workers-commission", "menu-workers-list", "button", "设置平台抽成", "", "workers.commission_set", 574, true),

  adminMenu("menu-finance", null, "directory", "财务", "/admin/finance/payments", "finance.payments.view", 500),
  adminMenu("menu-finance-payments", "menu-finance", "menu", "支付记录", "/admin/finance/payments", "finance.payments.view", 490),
  adminMenu("menu-finance-packages", "menu-finance", "menu", "充值套餐", "/admin/finance/recharge-packages", "finance.recharge_package.manage", 480),
  adminMenu("menu-finance-tips", "menu-finance", "menu", "打赏记录", "/admin/finance/tips", "finance.tips.view", 470),
  adminMenu("menu-finance-ledger", "menu-finance", "menu", "财务流水", "/admin/finance/ledger", "finance.ledger.view", 460),
  adminMenu("menu-finance-withdrawals", "menu-finance", "menu", "提现审核", "/admin/finance/withdrawals", "finance.withdraw.view", 450),
  adminMenu("btn-finance-withdraw-approve", "menu-finance-withdrawals", "button", "通过提现", "", "finance.withdraw.approve", 449, true),
  adminMenu("btn-finance-withdraw-reject", "menu-finance-withdrawals", "button", "拒绝提现", "", "finance.withdraw.reject", 448, true),
  adminMenu("btn-finance-withdraw-paid", "menu-finance-withdrawals", "button", "标记已打款", "", "finance.withdraw.mark_paid", 447, true),
  adminMenu("btn-finance-export", "menu-finance", "button", "财务导出", "", "finance.export", 446, true),

  adminMenu("menu-announcements", null, "directory", "营销", "/admin/announcements", "announcements.view", 400),
  adminMenu("menu-announcements-list", "menu-announcements", "menu", "公告列表", "/admin/announcements", "announcements.view", 390),
  adminMenu("btn-announcements-create", "menu-announcements-list", "button", "新增公告", "", "announcements.create", 389, true),
  adminMenu("btn-announcements-edit", "menu-announcements-list", "button", "编辑公告", "", "announcements.edit", 388, true),
  adminMenu("btn-announcements-delete", "menu-announcements-list", "button", "删除公告", "", "announcements.delete", 387, true),
  adminMenu("btn-announcements-archive", "menu-announcements-list", "button", "归档公告", "", "announcements.archive", 386, true),
  adminMenu("btn-announcements-pin", "menu-announcements-list", "button", "置顶公告", "", "announcements.pin", 385, true),

  adminMenu("menu-feedback", null, "directory", "反馈", "/admin/feedback", "feedback.feedback.view", 300),
  adminMenu("menu-feedback-list", "menu-feedback", "menu", "反馈列表", "/admin/feedback", "feedback.feedback.view", 290),
  adminMenu("menu-disputes", "menu-feedback", "menu", "订单投诉", "/admin/disputes", "feedback.complaints.view", 280),
  adminMenu("btn-feedback-handle", "menu-feedback", "button", "处理反馈", "", "feedback.feedback.reply", 279, true),
  adminMenu("btn-complaints-handle", "menu-disputes", "button", "处理投诉", "", "feedback.complaints.handle", 278, true),

  adminMenu("menu-permissions", null, "directory", "权限", "/admin/permissions/roles", "permissions.roles.manage", 200),
  adminMenu("menu-permissions-roles", "menu-permissions", "menu", "角色管理", "/admin/permissions/roles", "permissions.roles.manage", 190),
  adminMenu("menu-permissions-users", "menu-permissions", "menu", "管理员管理", "/admin/permissions/admin-users", "permissions.admin_users.manage", 180),
  adminMenu("menu-permissions-menus", "menu-permissions", "menu", "菜单管理", "/admin/permissions/menus", "permissions.menus.manage", 170),
  adminMenu("btn-permissions-assign", "menu-permissions-roles", "button", "分配权限", "", "permissions.assign", 169, true),

  adminMenu("menu-settings", null, "directory", "设置", "/admin/settings", "settings.view", 100),
  adminMenu("menu-settings-basic", "menu-settings", "menu", "基础设置", "/admin/settings", "settings.view", 90),
  adminMenu("btn-settings-edit", "menu-settings-basic", "button", "编辑设置", "", "settings.edit", 89, true),
];

const allAdminPermissionKeys = Array.from(new Set(initialAdminMenus.map((item) => item.permissionKey).filter(Boolean))) as string[];

export const initialAdminRoles: AdminRole[] = [
  {
    id: "role-super-admin",
    name: "超级管理员",
    code: "super_admin",
    description: "拥有小洛克电竞管理端全部权限",
    status: "enabled",
    permissions: allAdminPermissionKeys,
    builtIn: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "role-operations-admin",
    name: "运营管理员",
    code: "operations_admin",
    description: "负责统计、用户、订单、商品、接单员、公告与反馈处理",
    status: "enabled",
    permissions: allAdminPermissionKeys.filter((key) =>
      key.startsWith("dashboard.") ||
      key.startsWith("statistics.") ||
      key.startsWith("users.view") ||
      key.startsWith("orders.") ||
      key.startsWith("products.") ||
      key.startsWith("workers.view") ||
      key.startsWith("announcements.") ||
      key.startsWith("feedback."),
    ),
    builtIn: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "role-finance-admin",
    name: "财务管理员",
    code: "finance_admin",
    description: "负责支付记录、财务流水、提现审核和充值套餐",
    status: "enabled",
    permissions: allAdminPermissionKeys.filter((key) => key.startsWith("finance.") || key === "orders.view" || key === "orders.refund" || key === "dashboard.view"),
    builtIn: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "role-support-admin",
    name: "客服管理员",
    code: "support_admin",
    description: "负责订单查看、投诉反馈、用户查看和聊天记录",
    status: "enabled",
    permissions: ["dashboard.view", "orders.view", "users.view", "feedback.feedback.view", "feedback.feedback.reply", "feedback.complaints.view", "feedback.complaints.handle"],
    builtIn: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "role-readonly-admin",
    name: "只读管理员",
    code: "readonly_admin",
    description: "只能查看统计、订单、用户、商品和接单员信息",
    status: "enabled",
    permissions: allAdminPermissionKeys.filter((key) => key.endsWith(".view") || key === "dashboard.view" || key === "statistics.view"),
    builtIn: true,
    createdAt,
    updatedAt: createdAt,
  },
];

export const initialAdminUsers: AdminUser[] = [
  {
    id: "admin-user-root",
    username: "admin",
    password: "0000",
    name: "管理员",
    avatarUrl: "",
    status: "enabled",
    roleIds: ["role-super-admin"],
    lastLoginAt: "",
    lastLoginIp: "",
    createdAt,
    updatedAt: createdAt,
    builtIn: true,
  },
];

export const initialStore: StoreShape = {
  users: [],
  products: initialProducts,
  product_categories: initialProductCategories,
  workers: initialWorkers,
  announcements: initialAnnouncements,
  orders: [],
  wallet_accounts: [],
  wallet_ledger: [],
  recharge_orders: [],
  recharge_packages: initialRechargePackages,
  withdraw_requests: [],
  deposit_refunds: [],
  chat_sessions: [],
  chat_messages: [],
  admin_roles: initialAdminRoles,
  admin_users: initialAdminUsers,
  admin_menus: initialAdminMenus,
  admin_logs: [],
};
